const skillLevels = {
    JUNIOR: 'junior',
    INTERMEDIATE: 'intermediate',
    EXPERT: 'expert',
};

const yoonJi = "https://1.bp.blogspot.com/-apCJGz2OWqc/WXGlbrzvWkI/AAAAAAAAAgI/ghZSGVd3RK8dkVSWZ-7ngiQLbU-KTgDJQCLcBGAs/s1600/yoon-ji-seong-wanna-one-02.jpg";

export default [
    {
        id: 1,
        name: 'Johnny Sticks',
        username: 'Sticks',
        title: 'Designer',
        imageUrl: yoonJi,
        followers: 3450,
        following: 220,
        assisted: 120,
        associations: [],
        skillLevel: skillLevels.JUNIOR,
        portfolio: 'www.JohnnySticks.com',
        dribble: 'dribble.com/johhny',
        behance: 'behance.net/johnny',
        about: 'Johhny is a strategy-minded designer based in New York City. He independantly assists companies in creating lasting brand identities.',
    },
    {
        id: 2,
        name: 'Brett Lindholm',
        username: 'Splat',
        title: 'Head Creative',
        imageUrl: yoonJi,
        followers: 2142,
        following: 310,
        assisted: 211,
        associations: [],
        skillLevel: skillLevels.EXPERT,
        portfolio: 'www.brettSplatSticks.com',
        dribble: 'dribble.com/brettSplat',
        behance: null,
        about: 'Brett Lindholm is a strategy-minded designer based in New York City. He independantly assists companies in creating lasting brand identities.',
    },
    {
        id: 3,
        name: 'Ping Zoo',
        username: 'PingZoo',
        title: 'Illustrator',
        imageUrl: yoonJi,
        followers: 3450,
        following: 220,
        assisted: 120,
        associations: [],
        skillLevel: skillLevels.INTERMEDIATE,
        portfolio: 'www.PingZoo.com',
        dribble: 'dribble.com/PingZoo',
        behance: 'behance.net/PingZoo',
        about: 'Ping Zoo is a strategy-minded illustrator based in New York City. She independantly assists companies in creating lasting brand identities.',
    },
    {
        id: 4,
        name: 'James Victoire',
        username: 'victoire',
        title: 'Designer',
        imageUrl: yoonJi,
        followers: 3450,
        following: 220,
        assisted: 120,
        associations: [],
        skillLevel: skillLevels.INTERMEDIATE,
        portfolio: 'www.victoire.com',
        dribble: 'dribble.com/victoire',
        behance: 'behance.net/victoire',
        about: 'James Victoire is a designer based in New York City. He assists companies in creating lasting brand identities.',
    },
    {
        id: 5,
        name: 'Samantha Jones',
        username: 'slamantha',
        title: 'Freelance Designer',
        imageUrl: yoonJi,
        followers: 3450,
        following: 220,
        assisted: 120,
        associations: [],
        skillLevel: skillLevels.INTERMEDIATE,
        portfolio: 'www.slamantha.com',
        dribble: 'dribble.com/slamantha',
        behance: 'behance.net/slamantha',
        about: 'Samantha Jones is a freelance designer based in New York City. She assists companies in creating lasting brand identities.',
    },
    {
        id: 6,
        name: 'Allan Revah',
        username: 'revah',
        title: 'Designer',
        imageUrl: yoonJi,
        followers: 3450,
        following: 220,
        assisted: 120,
        associations: [],
        skillLevel: skillLevels.EXPERT,
        portfolio: 'www.revah.com',
        dribble: 'dribble.com/revah',
        behance: 'behance.net/revah',
        about: 'Allan Revah is a freelance designer based in New York City. He assists companies in creating lasting brand identities, in record time.',
    },
    {
        id: 7,
        name: 'Kim Ji',
        username: 'kimG',
        title: 'Designer',
        imageUrl: yoonJi,
        followers: 3450,
        following: 220,
        assisted: 120,
        associations: [],
        skillLevel: skillLevels.JUNIOR,
        portfolio: 'www.kimG.com',
        dribble: null,
        behance: null,
        about: 'Kim Ji is a designer based in New York City. He assists companies in creating lasting brand identities.',
    },
    {
        id: 8,
        name: 'April May',
        username: 'aprilM',
        title: 'Illustrator',
        imageUrl: yoonJi,
        followers: 3450,
        following: 220,
        assisted: 120,
        associations: [],
        skillLevel: skillLevels.EXPERT,
        portfolio: 'www.aprilM.com',
        dribble: 'dribble.com/aprilM',
        behance: 'behance.net/aprilM',
        about: 'April May is an illustrator based in New York City. She assists companies in creating lasting brand identities.',
    },
];
